dbooth_reverse_category_dict = {
    "backpack":'bag',
    'backpack_dog':'bag',
    'bear_plushie':'toy',
    'berry_bowl':'household object',
    'can':'household object',
    'candle':'household object',
    'cat':'pet animal',
    'cat2':'pet animal',
    'clock':'household animal',
    'colorful_sneaker':'shoe',
    'dog':'pet animal',
    'dog2':'pet animal',
    'dog3':'pet animal',
    'dog5':'pet animal',
    'dog6':'pet animal',
    'dog7':'pet animal',
    'dog8':'pet animal',
    'duck_toy':'toy',
    'fancy_boot':'shoe',
    'grey_sloth_plushie':'toy',
    'monster_toy':'toy',
    'pink_sunglasses':'glasses',
    'poop_emoji':'toy',
    'rc_car':'toy',
    'red_cartoon':'cartoon character',
    'robot_toy':'toy',
    'shiny_sneaker':'shoe',
    'teapot':'household object',
    'vase':'household object',
    'wolf_plushie':'toy'
    }
    
yollava_reverse_category_dict = {
    'ciin': 'person',
    'denisdang': 'person',
    'khanhvy': 'person',
    'oong': 'person',
    'phuc-map': 'person',
    'thao': 'person',
    'thuytien': 'person',
    'viruss': 'person',
    'yuheng': 'person',
    'willinvietnam': 'person',
    'chua-thien-mu': 'building',
    'nha-tho-hanoi': 'building',
    'nha-tho-hcm': 'building',
    'thap-but': 'building',
    'thap-cham': 'building',
    'dug': 'cartoon character',
    'fire': 'cartoon character',
    'marie-cat': 'cartoon character',
    'toodles-galore': 'cartoon character',
    'water': 'cartoon character',
    'bo': 'pet animal',
    'butin': 'pet animal',
    'henry': 'pet animal',
    'mam': 'pet animal',
    'mydieu': 'pet animal',
    'shiba-yellow': 'toy',
    'pusheen-cup': 'mug',
    'neurips-cup': 'toy',
    'tokyo-keyboard': 'electronic',
    'cat-cup': 'cup',
    'brown-duck': 'toy',
    'lamb': 'toy',
    'duck-banana': 'toy',
    'shiba-black': 'toy',
    'pig-cup': 'cup',
    'shiba-sleep': 'toy',
    'yellow-duck': 'toy',
    'elephant': 'toy',
    'shiba-gray': 'toy',
    'dragon': 'toy'
    }

myvlm_reverse_category_dict = {
    'asian_doll': 'toy',
    'boy_funko_pop': 'toy',
    'bull': 'figurine',
    'cat_statue': 'figurine',
    'ceramic_head': 'figurine',
    'chicken_bean_bag': 'toy',
    'colorful_teapot': 'tea pot',
    'dangling_child': 'toy',
    'elephant_sphere': 'figurine',
    'elephant_statue': 'figurine',
    'espresso_cup': 'cup',
    'gengar_toy': 'toy',
    'gold_pineapple': 'household object',
    'iverson_funko_pop':'toy',
    'green_doll': 'toy',
    'maeve_dog': 'pet animal',
    'minion_toy': 'toy',
    'rabbit_toy': 'toy',
    'red_chicken': 'figurine',
    'red_piggy_bank': 'piggy bank',
    'robot_toy': 'toy',
    'running_shoes': 'shoe',
    'sheep_pillow': 'pillow',
    'sheep_plush': 'toy',
    'sheep_toy': 'toy',
    'skulls_mug': 'mug',
    'small_penguin': 'toy',
    'billy_dog': 'pet animal',
    'my_cat': 'pet animal'
}